import { WebSocketServer } from "ws";
import { checkUser } from "./utils/checkUser";
import { JwtPayload } from "jsonwebtoken";
import { client } from "@repo/db/client";
import { greetApplicant } from "./utils/greetApplicant";
import { textToSpeech } from "./utils/elevenLabs";
import { saveToDB } from "./utils/saveToDB";
import { handleUserAnswer } from "./utils/userAnswer";
// import { client } from "@repo/db/client";

const wss = new WebSocketServer({ port: 8080, path: "/api/v1/interview" });

wss.on("connection", async function connection(ws, request) {
    ws.on("error", console.error);
    const url = request.url;
    if (!url) {
        return;
    }
    const queryParams = new URLSearchParams(url.split("?")[1]);
    const token = queryParams.get("token") || "";
    const { userId, interviewId, jobId } = checkUser(token) as JwtPayload;

    // bring all the data here for the convience and can be send to function required
    const userData = await client.user.findFirst({
        where: { id: userId },
    });

    const jobData = await client.job.findFirst({
        where: { id: jobId },
    });

    const interivewData = await client.interview.findFirst({
        where: { id: interviewId },
        include: { application: true },
    });

    // interviewStart -> greeting and introduction starting should have greeting function and details about the interview
    // for next question ai-bot can also have resume data like project that have done so far
    // experience and tech stack they used
    // fetch the user data and job data

    // for each question we can use eleven lab to convert the question that is generated by user and for each answer we can convert the answer which comes from frontend to backend to text then assess the answer and save it to db

    // now the question is should ask next question while assessing the answer or should i call another type of question which means

    // should i do some thing like this
    // sendGreetingQuestion type
    // assessAnswer and askNextQuestion in same or different?????

    let currentQuestionId: string | null = null;

    ws.on("message", async (data, isBinary) => {
        try {
            // If JSON message
            if (!isBinary) {
                const payload = JSON.parse(data.toString());

                switch (payload.type) {
                    case "Initiate_Interview": {
                        const greetingText = await greetApplicant(
                            userData,
                            jobData,
                            interivewData,
                        );

                        const questionId = await saveToDB(
                            greetingText,
                            interviewId,
                        );

                        const speech = await textToSpeech(greetingText);

                        ws.send(
                            JSON.stringify({
                                type: "AI_MESSAGE_START",
                                questionId,
                                text: greetingText,
                                audioIncoming: true,
                            }),
                        );

                        ws.send(speech);

                        ws.send(
                            JSON.stringify({
                                type: "AI_MESSAGE_END",
                                questionId,
                            }),
                        );

                        break;
                    }

                    case "ANSWER_FROM_USER": {
                        currentQuestionId = payload.questionId;
                        break;
                    }

                    case "END_INTERVIEW" : {
                        createReport(interviewId)
                    }
                }
            }

            // If Binary → This is user audio
            else {
                if (!currentQuestionId) return;

                const audioBuffer = Buffer.from(data as Buffer);

                await handleUserAnswer(
                    audioBuffer,
                    currentQuestionId,
                    interviewId,
                    ws,
                );

                currentQuestionId = null;
            }
        } catch (error) {
            console.error("WS ERROR:", error);
        }
    });
});
